
exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('students').del()
    .then(function () {
      const student = [
        {
          firstName: 'Nagy',
          lastName: 'Emese',
          birthPlace: 'Szeged',
          birthDate: '2000-01-01',
          nameOfMother: 'Csodás Mária',
          email: 'emese.nagy@gmail.com',
          telephoneNumber: '+36301234567',
          postCode: '6527',
          city: 'Szeged',
          address: 'Attila u. 4.',
          image: '../public/images/MB_GLE.jpg',
          studyYear_id: 1,
          classes_id: 2
        },
        {
          firstName: 'Kis',
          lastName: 'László',
          birthPlace: 'Dorozsma',
          birthDate: '2000-02-01',
          nameOfMother: 'Csodásabb Emília',
          email: 'laszlo.kis@gmail.com',
          telephoneNumber: '+36-30-124-5678',
          postCode: '6427',
          city: 'Szeged',
          address: 'Szilléri sgt. 4. 3. em. 12.',
          image: '../public/images/MB_GLE.jpg',
          studyYear_id: 2,
          classes_id: 3
        },
        {
          firstName: 'Kis-Nagy',
          lastName: 'Panna',
          birthPlace: 'Budapest',
          birthDate: '2000-03-01',
          nameOfMother: 'Ámulós Cilike',
          email: 'panna.kis-nagy@gmail.com',
          telephoneNumber: '+36-30-321-8765',
          postCode: '6210',
          city: 'Kiskunmajsa',
          address: 'Kossuth utca 12.',
          image: '../public/images/MB_GLE.jpg',
          studyYear_id: 2,
          classes_id: 3
        },
        {
          firstName: 'Ábrahám',
          lastName: 'Napsugár',
          birthPlace: 'Zsiráfia',
          birthDate: '2000-04-01',
          nameOfMother: 'Afrika Csillaga',
          email: 'sunset.abri@gmail.com',
          telephoneNumber: '+36-30-332-4007',
          postCode: '6327',
          city: 'Szeged',
          address: 'Szabadság u. 13.',
          image: '../public/images/MB_GLE.jpg',
          studyYear_id: 1,
          classes_id: 2
        },
        {
          firstName: 'Karate',
          lastName: 'Kid',
          birthPlace: 'Los Angeles',
          birthDate: '2000-07-01',
          nameOfMother: 'Zsib Vásárka',
          email: 'sunset.abri@gmail.com',
          telephoneNumber: '+36-30-672-9438',
          postCode: '6327',
          city: 'Szeged',
          address: 'Szabadság u. 13.',
          image: '../public/images/MB_GLE.jpg',
          studyYear_id: 1,
          classes_id: 3
        },
        {
          firstName: 'Tomoka',
          lastName: 'Nogaka',
          birthPlace: 'Rendőrakadémia',
          birthDate: '2000-01-01',
          nameOfMother: 'Tacsikava Husquana',
          email: 'sunset.abri@gmail.com',
          telephoneNumber: '+36-51-657-5021',
          postCode: '6327',
          city: 'Szeged',
          address: 'Szabadság u. 13.',
          image: '../public/images/MB_GLE.jpg',
          studyYear_id: 1,
          classes_id: 4
        },
        {
          firstName: 'Verbatim',
          lastName: 'Boglárka',
          birthPlace: 'Taxi hátsó ülése',
          birthDate: '2000-08-01',
          nameOfMother: 'Taxi Óra',
          email: 'sunset.abri@gmail.com',
          telephoneNumber: '+36-20-222-5577',
          postCode: '6327',
          city: 'Szeged',
          address: 'Szabadság u. 13.',
          image: '../public/images/MB_GLE.jpg',
          studyYear_id: 1,
          classes_id: 5
        },
        {
          firstName: 'Sterymar',
          lastName: 'Orrspayka',
          birthPlace: 'Merck',
          birthDate: '2000-05-01',
          nameOfMother: 'Floralys Medicus',
          email: 'sunset.abri@gmail.com',
          telephoneNumber: '+36-30-666-7458',
          postCode: '6327',
          city: 'Szeged',
          address: 'Szabadság u. 13.',
          image: '../public/images/MB_GLE.jpg',
          studyYear_id: 1,
          classes_id: 6
        },
        {
          firstName: 'Lenovo',
          lastName: 'Hajnala',
          birthPlace: 'Billentyűzetfalva',
          birthDate: '2000-04-08',
          nameOfMother: 'Silicon Valey',
          email: 'sunset.abri@gmail.com',
          telephoneNumber: '+36-30-555-8854',
          postCode: '6327',
          city: 'Szeged',
          address: 'Szabadság u. 13.',
          image: '../public/images/MB_GLE.jpg',
          studyYear_id: 1,
          classes_id: 7
        },
        {
          firstName: 'Police',
          lastName: 'Academy',
          birthPlace: 'Kutyafarka',
          birthDate: '2000-04-03',
          nameOfMother: 'Béke Pipa',
          email: 'sunset.abri@gmail.com',
          telephoneNumber: '+36-30-123-9876',
          postCode: '6327',
          city: 'Szeged',
          address: 'Szabadság u. 13.',
          image: '../public/images/MB_GLE.jpg',
          studyYear_id: 1,
          classes_id: 8
        },
        {
          firstName: 'Rahám',
          lastName: 'Sugár',
          birthPlace: 'Egérfalva',
          birthDate: '2000-04-02',
          nameOfMother: 'Afrika Hajnali',
          email: 'sunset.abri@gmail.com',
          telephoneNumber: '+36-30-123-4567',
          postCode: '6327',
          city: 'Szeged',
          address: 'Szabadság u. 13.',
          image: '../public/images/MB_GLE.jpg',
          studyYear_id: 1,
          classes_id: 9
        }
      ];
      return knex('students').insert(student);
    });
};
